# Generated by Django 5.1.4 on 2025-01-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'verbose_name': 'План', 'verbose_name_plural': 'Планы'},
        ),
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.AlterField(
            model_name='plan',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название плана'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], verbose_name='Приоритет задачи'),
        ),
    ]
